# Generated by Django 5.0.2 on 2024-02-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MyappUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=32)),
                ('password', models.CharField(default='', max_length=50)),
                ('history', models.IntegerField()),
            ],
            options={
                'db_table': 'site_users',
                'managed': True,
            },
        ),
    ]
