# Generated by Django 5.0.2 on 2024-02-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myappusers',
            name='history',
        ),
        migrations.RemoveField(
            model_name='myappusers',
            name='password',
        ),
        migrations.AddField(
            model_name='myappusers',
            name='password1',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='myappusers',
            name='password2',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='myappusers',
            name='password3',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
