# Generated by Django 5.0.2 on 2024-02-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_myappusers_history_remove_myappusers_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappusers',
            name='password4',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
