# Generated by Django 5.0.2 on 2024-02-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myappusers_password4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myappusers',
            name='password4',
        ),
    ]
