# Generated by Django 5.0.2 on 2024-02-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_myappusers_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappusers',
            name='password1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myappusers',
            name='password2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myappusers',
            name='password3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
