# Generated by Django 5.0.2 on 2024-02-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_myappusers_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappusers',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
